// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lafciilvzxtevdpqcfuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhZmNpaWx2enh0ZXZkcHFjZnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Nzk2OTQsImV4cCI6MjA2ODU1NTY5NH0.IN0J-xhhK16dK0Tr1RNZTQxvjt1X9zDTA5RL341Uur8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});